### ISSUE TITLE
Translation to Spanish

### ISSUE THREAD

**Issue by h771864** [UnlimitedHugs/RimworldAllowTool#1]
KeyBindingCategories--------------------------------------------------
<KeyBindingCategoryDefs>
	
	<KeyBindingCategoryDef>
		<defName>AllowTool</defName>
		<label>Allow Tool</label>
		<description>Designar accesos directos para el mod Allow Tool.</description>
		<checkForConflicts></checkForConflicts>
	</KeyBindingCategoryDef>
	
</KeyBindingCategoryDefs>

KeyBindings--------------------------------------------------
<KeyBindingDefs>
	
	<KeyBindingDef>
		<category>AllowTool</category>
		<defName>DesignatorAllow</defName>
		<label>Asignar: Permitir selección</label>
		<defaultKeyCodeA>U</defaultKeyCodeA>
	</KeyBindingDef>
	
	<KeyBindingDef>
		<category>AllowTool</category>
		<defName>DesignatorForbid</defName>
		<label>Asignar: Prohibir selección</label>
		<defaultKeyCodeA>I</defaultKeyCodeA>
	</KeyBindingDef>
	
	<KeyBindingDef>
		<category>AllowTool</category>
		<defName>DesignatorAllowAll</defName>
		<label>Asignar: Permitir todo</label>
	</KeyBindingDef>
	
	<KeyBindingDef>
		<category>AllowTool</category>
		<defName>DesignatorMassSelect</defName>
		<label>Asignar: Selección en masa</label>
		<defaultKeyCodeA>Y</defaultKeyCodeA>
	</KeyBindingDef>
	
</KeyBindingDefs>

Designators--------------------------------------------------
<Defs>
	
    <AllowTool.ThingDesignatorDef>
        <defName>AllowDesignator</defName>
		
		<designatorClass>AllowTool.Designator_Allow</designatorClass>
        
		<hidden>false</hidden>
		
		<category>Orders</category>
		
		<insertAfter>Designator_Claim</insertAfter>
		
        <label>Permitir selección</label>
		
		<description>Permite todos los objetos en el área seleccionada.
Clicar y arrastrar sobre el área para usar.</description>
		
		<iconTex>allow</iconTex>
		
		<dragHighlightTex>allowHighlight</dragHighlightTex>
		
		<soundSucceded>TickHigh</soundSucceded>
		
		<hotkeyDef>DesignatorAllow</hotkeyDef>
		
		<messageSuccess>Allow_area_success</messageSuccess>
		
		<messageFailure>Allow_area_failure</messageFailure>
	</AllowTool.ThingDesignatorDef>
	
    <AllowTool.ThingDesignatorDef>
        <defName>ForbidDesignator</defName>
		<designatorClass>AllowTool.Designator_Forbid</designatorClass>
        <hidden>false</hidden>
		<category>Orders</category>
		<insertAfter>AllowTool.Designator_Allow</insertAfter>
        <label>Prohibir selección</label>
		<description>Prohíbe todos los objetos en el área seleccionada.
Clicar y arrastrar sobre el área para usar.</description>
		<iconTex>forbid</iconTex>
		<dragHighlightTex>forbidHighlight</dragHighlightTex>
		<soundSucceded>TickLow</soundSucceded>
		<hotkeyDef>DesignatorForbid</hotkeyDef>
		<messageSuccess>Forbid_area_success</messageSuccess>
		<messageFailure>Forbid_area_failure</messageFailure>
	</AllowTool.ThingDesignatorDef>
	
    <AllowTool.ThingDesignatorDef>
        <defName>AllowAllDesignator</defName>
		<designatorClass>AllowTool.Designator_AllowAll</designatorClass>
        <hidden>false</hidden>
		<category>Orders</category>
		<insertAfter>AllowTool.Designator_Forbid</insertAfter>
        <label>Permitir todo</label>
		<description>Permite todos los objetos en el mapa.
Clic para activar.
Mantener shift para incluir esqueletos y cadáveres podridos.</description>
		<iconTex>allowAll</iconTex>
		<dragHighlightTex>allowHighlight</dragHighlightTex>
		<soundSucceded>TickHigh</soundSucceded>
		<hotkeyDef>DesignatorAllowAll</hotkeyDef>
		<messageSuccess>Allow_all_success</messageSuccess>
		<messageFailure>Allow_all_failure</messageFailure>
	</AllowTool.ThingDesignatorDef>
	
    <AllowTool.ThingDesignatorDef>
        <defName>MassSelectDesignator</defName>
		<designatorClass>AllowTool.Designator_MassSelect</designatorClass>
        <hidden>false</hidden>
		<category>Orders</category>
		<insertAfter>AllowTool.Designator_AllowAll</insertAfter>
        <label>Selección en masa</label>
		<description>Selecciona todo en un área, ignorando los limites de detección o selección comunes. Seleccionar demasiadas cosas a la vez puede ralentizar el juego- usar con cuidado.
Mantener shift par añadir a la selección actual.
Mantener control/Opciones para invertir la selección.</description>
		<iconTex>massSelect</iconTex>
		<dragHighlightTex>massSelectHighlight</dragHighlightTex>
		<soundSucceded>ThingSelected</soundSucceded>
		<hotkeyDef>DesignatorMassSelect</hotkeyDef>
	</AllowTool.ThingDesignatorDef>
	
</Defs>

AllowToolStrings--------------------------------------------------
<LanguageData>

	<Allow_area_success>Permitidos {0} objetos.</Allow_area_success>
	<Allow_area_failure>No se encontraron objetos prohibidos.</Allow_area_failure>

	<Forbid_area_success>Prohibidos {0} objetos.</Forbid_area_success>
	<Forbid_area_failure>No se encontraron artículos prohibibles.</Forbid_area_failure>
	
	<Allow_all_success>Permitidas {0} cosas en todo el mapa.</Allow_all_success>
	<Allow_all_failure>No se encontraron cosas prohibidas.</Allow_all_failure>
	
</LanguageData>

A greeting and thanks for your work!

**Comment by UnlimitedHugs** [comment]
Hello!
It's good, but incomplete- DefInjected strings are also required for this file:
AllowTool/Defs/ThingDesignatorDefs/Designators.xml (fields: label and description)
KeyBindingCategoryDefs and KeyBindingDefs also contain translatable text, if you want to be thorough.
 
You can check your Rimworld folder if you want to learn how to make DefInjected translations:
Mods/Core/Languages/Spanish/DefInjected
You can also make a pull request with the new files for some extra fun and to make my life easier :)

**Comment by h771864** [comment]
I edited the first post with all the texts, sorry! I am a newbie and do not know how this works. I hope to help more and make things easier in the future ^^

To facilitate reading and/or copying (Designators is annoying!)
http://pastebin.com/rUSPkNF8

**Comment by UnlimitedHugs** [comment]
Released the translated version. Thank you for the contribution.
