### ISSUE TITLE
Exception during PrepareContextMenus

### ISSUE THREAD

**Issue by xrogaan** [UnlimitedHugs/RimworldAllowTool#17]
I opened a thread on the steam mod page, but to be sure I'll open a ticket here too as it seems to be the proper place and it is more convenient.

The exception is thrown right after embarking.

```
[AllowTool][ERR] Exception during PrepareContextMenus: System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
  at System.Collections.Generic.List`1+Enumerator[Verse.Designator].VerifyState () [0x00000] in <filename unknown>:0 
  at System.Collections.Generic.List`1+Enumerator[Verse.Designator].MoveNext () [0x00000] in <filename unknown>:0 
  at System.Linq.Enumerable+<CreateSelectManyIterator>c__Iterator12`2[Verse.DesignationCategoryDef,Verse.Designator].MoveNext () [0x00000] in <filename unknown>:0 
  at AllowTool.Context.DesignatorContextMenuController.PrepareContextMenus () [0x00000] in <filename unknown>:0 
Verse.Log:Error(String)
HugsLib.Utils.ModLogger:ReportException(Exception, String, Boolean, String)
AllowTool.Context.DesignatorContextMenuController:PrepareContextMenus()
AllowTool.AllowToolController:WorldLoaded()
HugsLib.HugsLibController:OnPlayingStateEntered()
HugsLib.Patches.Game_FinalizeInit_Patch:WorldLoadedHook()
Verse.Game:FinalizeInit_Patch1(Object)
Verse.Game:InitNewGame_Patch1(Object)
Verse.Root_Play:<Start>m__1()
Verse.LongEventHandler:RunEventFromAnotherThread(Action)
Verse.LongEventHandler:<UpdateCurrentAsynchronousEvent>m__1()
```

I have other weird stuff going on in the log, especially with the different `FAILED: Alien_Orassan`. I am wondering if the state my mods are in is clean.

[output_log.txt](https://github.com/UnlimitedHugs/RimworldAllowTool/files/1494597/output_log.txt)

**Comment by UnlimitedHugs** [comment]
This has been an elusive one. Are you getting this consistently?
It's safe to ignore, but I still would like it fixed.

**Comment by UnlimitedHugs** [comment]
Allright, I'll see if I can reproduce it.

**Comment by xrogaan** [comment]
I got an idea as why this happens, along with the other "failed" in the log. I just woke up, so this might be gibberish.

Given that mods relies on a specific state to function properly, that state may differ between a new game and a loaded game. Some elements could be different or non existent right after a new game, which lead to that exception or the other "failures" related to new races.

Because the game is creating a new game, and thus loading plenty of things in it, the collection you are trying to parse may be modified as it happens? Basically, could this be a load order issue?

**Comment by UnlimitedHugs** [comment]
Good thinking, but can't be the case here. My guess is it's a race condition.
I've got a potential fix for that lined up- coming in the next patch.

**Comment by UnlimitedHugs** [comment]
Any luck with the new build?

**Comment by xrogaan** [comment]
Everything seems fine now. No error in the log or in game.

(I tried answering with through email, but the message hasn't yet showed up. I may have failed to send the email to the right address, but just in case don't freak out if there is a duplicate showing up.)

**Comment by UnlimitedHugs** [comment]
Very nice. Thank you for taking the time to investigate this.
