### ISSUE TITLE
Cancel all of this type not working for mining

### ISSUE THREAD

**Issue by facejets** [UnlimitedHugs/RimworldAllowTool#25]
If I understand what expected behavior is, I found a bug: right-clicking cancel with a square of resources to be mined gives a choice to "cancel all of this type" that does not do anything, spitting "Select something with an order to cancel all orders of that type" at the top of the screen.  My About.xml's say target version is 1.0.2059

**Comment by UnlimitedHugs** [comment]
Good find.
This happens because Mine orders apply to tiles, rather than things, and need to be handled separately.

**Comment by UnlimitedHugs** [comment]
Fixed in [3.6.3](https://github.com/UnlimitedHugs/RimworldAllowTool/releases/tag/v3.6.3), including Mine, Plan and other tile designations.
