### ISSUE TITLE
Multiplayer mod compatibility

### ISSUE THREAD

**Issue by Dutchy-** [UnlimitedHugs/RimworldAllowTool#26]
It would be great if this mod was compatible with multiplayer.

https://docs.google.com/spreadsheets/d/1jaDxV8F7bcz4E9zeIRmZGKuaX7d0kvWWq28aKckISaY/edit#gid=0

It's currently listed as:
> Forbid, unforbid, select similar, haul urgently and finish off doesn't work.

I do not know if this is an issue in the Multiplayer mod or in this mod.

**Comment by MarcoMartins86** [comment]
There is this fork of 3.9.0 that claims to be compatible
https://github.com/rwmt/Multiplayer
