### ISSUE TITLE
Bug with 1.1

### ISSUE THREAD

**Issue by Xsowksi** [UnlimitedHugs/RimworldAllowTool#30]
When I draft the pawn, the undraft button disappears. I tried it with: Hugslib, Allow Tool and DLC on ver. 1.1, here I`m adding the log.
[log_only_allowtool.txt](https://github.com/UnlimitedHugs/RimworldAllowTool/files/4293954/log_only_allowtool.txt)

I hope that there is a fix for this.

Regards :)

**Comment by Xsowksi** [comment]
My bad. I forgot to turn off my little mod, which was doing that, I`m so sorry.

**Comment by UnlimitedHugs** [comment]
No worries :)
