### ISSUE TITLE
Add mass surgeries feature

### ISSUE THREAD

**Issue by loscil06** [UnlimitedHugs/RimworldAllowTool#31]
Hello! Thanks for such great mod.
I've come to a situation in which it'd be awesome if there was a new feature for applying to multiple selected pawns one type of surgery. The new functionality would work in the following way:
>select multiple pawns 
>an icon in the GUI will appear, named "Apply Surgery", along of course other actions such as finish off or strip
>upon clicking "Apply Surgery", a menu will pop-up and you can select the surgery you'd like to perform for all pawns selected: the surgery will appear in Operations tab for each pawn

If a pawn is not a proper candidate for such surgery, a notification will appear telling the user that "Surgery X cannot be applied to Pawn Y" or something like that.

Cases in which this feature would be useful: 
>a huge raid came and you emerged victorious. Since you need a way to recoup the costs you decide to harvest organs from prisoners. Selecting each prisoner and applying the same surgery is time consuming
>you got in your hands some much powerful new hardware such bunch of bionic/archotech legs or arms. You decide it's time for an upgrade for your colonists so you select them and the corresponding surgeries

I know it's asking too much, I've searched the internet and it appears no such mod already exists. Since it's a matter of QoL tool, I think it's proper this would-be feature be included in this mod.
Please consider and if there's something I could help I'd be glad to do so.

**Comment by UnlimitedHugs** [comment]
Hello!
This seems like a very niche feature to include in Allow Tool, not to mention that I would have to be the one to write and maintain it for eons to come. So, that would be a no for me.
However, I always like to encourage people to try their hand at making mods themselves- it's not as hard as it seems, and it far outranks simply playing the game when it comes to the fun factor.
