### ISSUE TITLE
Anima tree should not be affected by bulk woodcutting and harvesting commands

### ISSUE THREAD

**Issue by kampangs** [UnlimitedHugs/RimworldAllowTool#35]
The anima tree is not like other trees. Cutting it down is harmful and costly. It shouldn't be automatically cut down as part of a bulk woodcutting command from a tool's right click menu.

Chop all wood in map / home area and harvest fully grown plants in map / home area are affected. Maybe others.

**Comment by UnlimitedHugs** [comment]
Implemented in 3.10.0.
