### ISSUE TITLE
HaulUrgently workgiver tanks a lot of perfomance while having 0 items to haul with it

### ISSUE THREAD

**Issue by bustedbunny** [UnlimitedHugs/RimworldAllowTool#40]
![image](https://user-images.githubusercontent.com/30902981/135614726-0faf82ea-31fe-4907-8a1f-375c31273921.png)
With modified Wiri fork of Dubs Perfomance Analyzer I was able to store data about 1 full in-game day in late game colony.
So far, I have 0 items marked with haul urgently designation. Yet it's workgiver takes the most CPU time.
As suggestion:
It can be optimised by using AnySpawnedDesignationOfDef of DesignationManager in ShouldSkip.

**Comment by UnlimitedHugs** [comment]
Hey, appreciate the report. However, `HaulUrgentlyRefill` is not part of AllowTool, must have been added by another mod.
I might still add the precheck you suggested, though.
